import type { CommunityPost } from "./stores/community-store"

export function generateMockPosts(): CommunityPost[] {
  const posts: CommunityPost[] = [
    {
      id: "post-1",
      userId: "user-1",
      userName: "María González",
      userAvatar: "/placeholder.svg?height=40&width=40",
      userType: "lector",
      bookId: "book-1",
      bookTitle: "El Laberinto de los Sueños",
      bookCover: "/placeholder.svg?height=60&width=40",
      content:
        "Esta frase me llegó al alma: 'Los sueños son el lenguaje secreto del universo, y solo aquellos que se atreven a perderse en el laberinto pueden encontrar la salida hacia la verdad.'",
      type: "text",
      likes: 24,
      superlikes: 8,
      shares: 3,
      isLiked: false,
      isSuperliked: false,
      isShared: false,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      id: "post-2",
      userId: "user-2",
      userName: "Carlos Ruiz",
      userAvatar: "/placeholder.svg?height=40&width=40",
      userType: "escritor",
      bookId: "book-2",
      bookTitle: "Crónicas del Tiempo Perdido",
      bookCover: "/placeholder.svg?height=60&width=40",
      content: "Inspirado por este increíble pasaje sobre viajes en el tiempo",
      image: "/placeholder.svg?height=300&width=400",
      type: "image",
      likes: 156,
      superlikes: 42,
      shares: 18,
      isLiked: true,
      isSuperliked: false,
      isShared: false,
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    },
    {
      id: "post-3",
      userId: "user-3",
      userName: "Ana Martín",
      userAvatar: "/placeholder.svg?height=40&width=40",
      userType: "lector",
      bookId: "book-3",
      bookTitle: "Sombras en la Niebla",
      bookCover: "/placeholder.svg?height=60&width=40",
      content:
        "No puedo parar de leer este libro de terror. Esta escena me tiene sin dormir: 'La niebla se espesaba con cada paso, y las sombras parecían cobrar vida propia, susurrando secretos que nadie debería escuchar.'",
      type: "text",
      likes: 89,
      superlikes: 23,
      shares: 12,
      isLiked: false,
      isSuperliked: true,
      isShared: false,
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    },
    {
      id: "post-4",
      userId: "user-4",
      userName: "Diego López",
      userAvatar: "/placeholder.svg?height=40&width=40",
      userType: "escritor",
      bookId: "book-4",
      bookTitle: "El Jardín de los Secretos",
      bookCover: "/placeholder.svg?height=60&width=40",
      content: "Recreando la escena más romántica del libro",
      image: "/placeholder.svg?height=300&width=400",
      type: "image",
      likes: 203,
      superlikes: 67,
      shares: 34,
      isLiked: true,
      isSuperliked: true,
      isShared: false,
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    },
    {
      id: "post-5",
      userId: "user-5",
      userName: "Laura Fernández",
      userAvatar: "/placeholder.svg?height=40&width=40",
      userType: "lector",
      bookId: "book-5",
      bookTitle: "Voces del Abismo",
      bookCover: "/placeholder.svg?height=60&width=40",
      content:
        "Esta reflexión filosófica me hizo replantear todo: 'En el abismo de nuestras decisiones, las voces que escuchamos no son ecos del pasado, sino susurros del futuro que aún podemos cambiar.'",
      type: "text",
      likes: 67,
      superlikes: 19,
      shares: 8,
      isLiked: false,
      isSuperliked: false,
      isShared: true,
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    },
  ]

  return posts
}
