import type { Book } from "./stores/books-store"

export function generateMockLibrary(): Book[] {
  return [
    {
      id: "lib-1",
      title: "El Laberinto de los Sueños",
      author: "Elena Martínez",
      cover: "/placeholder.svg?height=400&width=300",
      category: "fantasia",
      reads: 5420,
      rating: 4.5,
      reviews: 234,
      description: "Una fascinante historia de fantasía...",
      isPurchased: true,
      readingProgress: 75,
    },
    {
      id: "lib-2",
      title: "Crónicas del Tiempo Perdido",
      author: "Carlos Ruiz",
      cover: "/placeholder.svg?height=400&width=300",
      category: "ciencia-ficcion",
      reads: 3210,
      rating: 4.2,
      reviews: 156,
      description: "Una aventura de ciencia ficción...",
      isPurchased: false,
      readingProgress: 45,
    },
    {
      id: "lib-3",
      title: "Sombras en la Niebla",
      author: "Ana García",
      cover: "/placeholder.svg?height=400&width=300",
      category: "terror",
      reads: 2890,
      rating: 4.7,
      reviews: 189,
      description: "Una historia de terror psicológico...",
      isPurchased: true,
      readingProgress: 100,
    },
    {
      id: "lib-4",
      title: "El Jardín de los Secretos",
      author: "Miguel Santos",
      cover: "/placeholder.svg?height=400&width=300",
      category: "romance",
      reads: 4560,
      rating: 4.3,
      reviews: 267,
      description: "Una historia romántica...",
      isPurchased: false,
      readingProgress: 20,
    },
  ]
}
